language: cpp
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - clang-6.0
      - ninja-build
      - shunit2
  homebrew:
    packages:
      - ninja
      - shunit2

os: linux
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - mkdir build && cd build && cmake .. -G Ninja
  - cmake --build . --config Debug
  - ctest -C Debug
  - cd ..
  - ./test/test-program-termination.sh
