# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  channel:
    description: "The channel for the package (i.e. user/channel)"
    required: true
  conan-login: # id of input
    description: "bintray username"
    required: true
  conan-pass:
    description: "bintray token"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
