name: C/C++ CI

on:
  - push
  - pull_request

jobs:
  custom-conan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy-conan-to-bintray
        with:
          who-to-greet: "junk"
        id: conan-deploy
      - name: get output
        run: echo "output ${{steps.conan-deploy.msg}}"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build ./build
      - name: ctest
        run: cd build && ctest ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v1
      - name: dependency-install
        run: sudo apt install -y python3-pip python3-setuptools
      - name: conan-install
        run: sudo pip3 install conan
      - name: conan-remote
        run: conan remote add bernedom https://api.bintray.com/conan/bernedom/conan
      - name: create-package
        run: conan create . bertrand/unstable
      - name: upload-package
        env:
          CONAN_LOGIN_USERNAME: ${{secrets.CONAN_LOGIN_USERNAME}}
          CONAN_PASSWORD: ${{secrets.CONAN_PASSWORD}}
        run: conan upload bertrand/*@bertrand/unstable --all -c -r bernedom
