name: C/C++ CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: sudo apt install shunit2 ninja-build -y
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build ./build
      - name: ctest
        run: cd build && ctest ./build
      - name: program-termination-tests
        run: ./test/test-program-termination.sh

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: cmake
        run: mkdir build; cd build; cmake .. -G "Visual Studio 16 2019" -A x64
      - name: build
        run: cmake --build . --config Debug
        working-directory: ./build
      - name: ctest
        run: ctest -C Debug
        working-directory: ./build
      - name: build-release
        run: cmake --build . --config Release
        working-directory: ./build

  installation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/installation-tests
        with:
          script: ./test/installation-tests.sh
        id: installation-tests

  deploy-to-conan:
    needs: [build, installation-tests, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy-conan-to-bintray
        with:
          conan_package: bertrand
          conan_channel: bertrand/unstable
          conan_remote: "https://api.bintray.com/conan/bernedom/conan"
          conan_user: ${{secrets.CONAN_LOGIN_USERNAME}}
          conan_pass: ${{secrets.CONAN_PASSWORD}}
        id: conan-deploy
