name: C/C++ CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: sudo apt install shunit2 ninja-build -y
      - name: cmake
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build ./build
      - name: ctest
        run: cd build && ctest ./build
      - name: program-termination-tests
        run: ./test/test-program-termination.sh

  installation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: sudo apt install shunit2 ninja-build -y
      - name: installation-tests
        run: ./test/installation-tests.sh

  deploy-to-conan:
    needs: [build, installation-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy-conan-to-bintray
        with:
          conan_package: bertrand
          conan_channel: bertrand/unstable
          conan_remote: "https://api.bintray.com/conan/bernedom/conan"
          conan_user: ${{secrets.CONAN_LOGIN_USERNAME}}
          conan_pass: ${{secrets.CONAN_PASSWORD}}
        id: conan-deploy
